<?php

/**
 * Implements hook_menu_alter().
 */
function lus_og_fix_menu_alter(&$items) {

}

function lus_og_fix_file_entity_access($op, $file, $account = NULL) {

  if ($account == NULL) {
    global $user;
    $account = $user;
  }

  if (is_null($file)) {
    $type = NULL;
  }
  else {
    $type = is_string($file) ? $file : (is_array($file) ? $file['type'] : $file->type);
  }

  if ($op == 'create' && og_is_group_content_type('file', $type)) {
// TODO: FIX ME
dpm('TODO: FIX ME.1');
  }
  elseif (in_array($op, array('update', 'delete')) && og_is_group_content_type('file', $type)) {
// TODO: FIX ME
dpm('TODO: FIX ME.2');
  }
  elseif (in_array($op, array('view', 'download')) && og_is_group_content_type('file', $type)) {

    $in_group = FALSE;

    foreach (og_get_entity_groups('file', $file) as $group_entity_type => $ids) {
      foreach ($ids as $id) {
        if (og_get_membership($group_entity_type, $id, 'user', $account->uid)) {
          $in_group = TRUE;
        }
      }
    }

    if ($in_group) {
      return FILE_ENTITY_ACCESS_ALLOW;
    }
    else {
      return FILE_ENTITY_ACCESS_DENY;
    }
  }

  // Default to deny. We're all about privacy.
  return FILE_ENTITY_ACCESS_DENY;
}
